/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthenticatedAuctioneerRouteImport } from './routes/_authenticated/auctioneer'
import { Route as AuthenticatedBookmarksRouteImport } from './routes/_authenticated/bookmarks'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as RegisterPlayerAuctionIdRouteImport } from './routes/register-player.$auctionId'
import { Route as AuthenticatedAuctionsIdRouteImport } from './routes/_authenticated/auctions.$id'
import { Route as AuthenticatedMyAuctionsIndexRouteImport } from './routes/_authenticated/my-auctions.index'
import { Route as AuthenticatedMyAuctionsNewRouteImport } from './routes/_authenticated/my-auctions.new'
import { Route as AuthenticatedPlayersPhoneRouteImport } from './routes/_authenticated/players.$phone'
import { Route as AuthenticatedMyAuctionsIdIndexRouteImport } from './routes/_authenticated/my-auctions.$id.index'
import { Route as AuthenticatedMyAuctionsIdAuctioneerRouteImport } from './routes/_authenticated/my-auctions.$id.auctioneer'
import { Route as AuthenticatedMyAuctionsIdEditRouteImport } from './routes/_authenticated/my-auctions.$id.edit'
import { Route as AuthenticatedMyAuctionsIdTeamsTeamIdRouteImport } from './routes/_authenticated/my-auctions.$id.teams.$teamId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuctioneerRoute = AuthenticatedAuctioneerRouteImport.update({
  id: '/auctioneer',
  path: '/auctioneer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookmarksRoute = AuthenticatedBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RegisterPlayerAuctionIdRoute = RegisterPlayerAuctionIdRouteImport.update({
  id: '/register-player/$auctionId',
  path: '/register-player/$auctionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAuctionsIdRoute = AuthenticatedAuctionsIdRouteImport.update({
  id: '/auctions/$id',
  path: '/auctions/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyAuctionsIndexRoute =
  AuthenticatedMyAuctionsIndexRouteImport.update({
    id: '/my-auctions/',
    path: '/my-auctions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyAuctionsNewRoute =
  AuthenticatedMyAuctionsNewRouteImport.update({
    id: '/my-auctions/new',
    path: '/my-auctions/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlayersPhoneRoute =
  AuthenticatedPlayersPhoneRouteImport.update({
    id: '/players/$phone',
    path: '/players/$phone',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyAuctionsIdIndexRoute =
  AuthenticatedMyAuctionsIdIndexRouteImport.update({
    id: '/my-auctions/$id/',
    path: '/my-auctions/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyAuctionsIdAuctioneerRoute =
  AuthenticatedMyAuctionsIdAuctioneerRouteImport.update({
    id: '/my-auctions/$id/auctioneer',
    path: '/my-auctions/$id/auctioneer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyAuctionsIdEditRoute =
  AuthenticatedMyAuctionsIdEditRouteImport.update({
    id: '/my-auctions/$id/edit',
    path: '/my-auctions/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyAuctionsIdTeamsTeamIdRoute =
  AuthenticatedMyAuctionsIdTeamsTeamIdRouteImport.update({
    id: '/my-auctions/$id/teams/$teamId',
    path: '/my-auctions/$id/teams/$teamId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/auctioneer': typeof AuthenticatedAuctioneerRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/register-player/$auctionId': typeof RegisterPlayerAuctionIdRoute
  '/auctions/$id': typeof AuthenticatedAuctionsIdRoute
  '/my-auctions/new': typeof AuthenticatedMyAuctionsNewRoute
  '/players/$phone': typeof AuthenticatedPlayersPhoneRoute
  '/my-auctions/': typeof AuthenticatedMyAuctionsIndexRoute
  '/my-auctions/$id/auctioneer': typeof AuthenticatedMyAuctionsIdAuctioneerRoute
  '/my-auctions/$id/edit': typeof AuthenticatedMyAuctionsIdEditRoute
  '/my-auctions/$id/': typeof AuthenticatedMyAuctionsIdIndexRoute
  '/my-auctions/$id/teams/$teamId': typeof AuthenticatedMyAuctionsIdTeamsTeamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/auctioneer': typeof AuthenticatedAuctioneerRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/register-player/$auctionId': typeof RegisterPlayerAuctionIdRoute
  '/auctions/$id': typeof AuthenticatedAuctionsIdRoute
  '/my-auctions/new': typeof AuthenticatedMyAuctionsNewRoute
  '/players/$phone': typeof AuthenticatedPlayersPhoneRoute
  '/my-auctions': typeof AuthenticatedMyAuctionsIndexRoute
  '/my-auctions/$id/auctioneer': typeof AuthenticatedMyAuctionsIdAuctioneerRoute
  '/my-auctions/$id/edit': typeof AuthenticatedMyAuctionsIdEditRoute
  '/my-auctions/$id': typeof AuthenticatedMyAuctionsIdIndexRoute
  '/my-auctions/$id/teams/$teamId': typeof AuthenticatedMyAuctionsIdTeamsTeamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/_authenticated/auctioneer': typeof AuthenticatedAuctioneerRoute
  '/_authenticated/bookmarks': typeof AuthenticatedBookmarksRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/register-player/$auctionId': typeof RegisterPlayerAuctionIdRoute
  '/_authenticated/auctions/$id': typeof AuthenticatedAuctionsIdRoute
  '/_authenticated/my-auctions/new': typeof AuthenticatedMyAuctionsNewRoute
  '/_authenticated/players/$phone': typeof AuthenticatedPlayersPhoneRoute
  '/_authenticated/my-auctions/': typeof AuthenticatedMyAuctionsIndexRoute
  '/_authenticated/my-auctions/$id/auctioneer': typeof AuthenticatedMyAuctionsIdAuctioneerRoute
  '/_authenticated/my-auctions/$id/edit': typeof AuthenticatedMyAuctionsIdEditRoute
  '/_authenticated/my-auctions/$id/': typeof AuthenticatedMyAuctionsIdIndexRoute
  '/_authenticated/my-auctions/$id/teams/$teamId': typeof AuthenticatedMyAuctionsIdTeamsTeamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/pricing'
    | '/auctioneer'
    | '/bookmarks'
    | '/profile'
    | '/register-player/$auctionId'
    | '/auctions/$id'
    | '/my-auctions/new'
    | '/players/$phone'
    | '/my-auctions/'
    | '/my-auctions/$id/auctioneer'
    | '/my-auctions/$id/edit'
    | '/my-auctions/$id/'
    | '/my-auctions/$id/teams/$teamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/pricing'
    | '/auctioneer'
    | '/bookmarks'
    | '/profile'
    | '/register-player/$auctionId'
    | '/auctions/$id'
    | '/my-auctions/new'
    | '/players/$phone'
    | '/my-auctions'
    | '/my-auctions/$id/auctioneer'
    | '/my-auctions/$id/edit'
    | '/my-auctions/$id'
    | '/my-auctions/$id/teams/$teamId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/pricing'
    | '/_authenticated/auctioneer'
    | '/_authenticated/bookmarks'
    | '/_authenticated/profile'
    | '/register-player/$auctionId'
    | '/_authenticated/auctions/$id'
    | '/_authenticated/my-auctions/new'
    | '/_authenticated/players/$phone'
    | '/_authenticated/my-auctions/'
    | '/_authenticated/my-auctions/$id/auctioneer'
    | '/_authenticated/my-auctions/$id/edit'
    | '/_authenticated/my-auctions/$id/'
    | '/_authenticated/my-auctions/$id/teams/$teamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  RegisterPlayerAuctionIdRoute: typeof RegisterPlayerAuctionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/auctioneer': {
      id: '/_authenticated/auctioneer'
      path: '/auctioneer'
      fullPath: '/auctioneer'
      preLoaderRoute: typeof AuthenticatedAuctioneerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookmarks': {
      id: '/_authenticated/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AuthenticatedBookmarksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/register-player/$auctionId': {
      id: '/register-player/$auctionId'
      path: '/register-player/$auctionId'
      fullPath: '/register-player/$auctionId'
      preLoaderRoute: typeof RegisterPlayerAuctionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/auctions/$id': {
      id: '/_authenticated/auctions/$id'
      path: '/auctions/$id'
      fullPath: '/auctions/$id'
      preLoaderRoute: typeof AuthenticatedAuctionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-auctions/': {
      id: '/_authenticated/my-auctions/'
      path: '/my-auctions'
      fullPath: '/my-auctions/'
      preLoaderRoute: typeof AuthenticatedMyAuctionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-auctions/new': {
      id: '/_authenticated/my-auctions/new'
      path: '/my-auctions/new'
      fullPath: '/my-auctions/new'
      preLoaderRoute: typeof AuthenticatedMyAuctionsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/players/$phone': {
      id: '/_authenticated/players/$phone'
      path: '/players/$phone'
      fullPath: '/players/$phone'
      preLoaderRoute: typeof AuthenticatedPlayersPhoneRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-auctions/$id/': {
      id: '/_authenticated/my-auctions/$id/'
      path: '/my-auctions/$id'
      fullPath: '/my-auctions/$id/'
      preLoaderRoute: typeof AuthenticatedMyAuctionsIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-auctions/$id/auctioneer': {
      id: '/_authenticated/my-auctions/$id/auctioneer'
      path: '/my-auctions/$id/auctioneer'
      fullPath: '/my-auctions/$id/auctioneer'
      preLoaderRoute: typeof AuthenticatedMyAuctionsIdAuctioneerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-auctions/$id/edit': {
      id: '/_authenticated/my-auctions/$id/edit'
      path: '/my-auctions/$id/edit'
      fullPath: '/my-auctions/$id/edit'
      preLoaderRoute: typeof AuthenticatedMyAuctionsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-auctions/$id/teams/$teamId': {
      id: '/_authenticated/my-auctions/$id/teams/$teamId'
      path: '/my-auctions/$id/teams/$teamId'
      fullPath: '/my-auctions/$id/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedMyAuctionsIdTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAuctioneerRoute: typeof AuthenticatedAuctioneerRoute
  AuthenticatedBookmarksRoute: typeof AuthenticatedBookmarksRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAuctionsIdRoute: typeof AuthenticatedAuctionsIdRoute
  AuthenticatedMyAuctionsNewRoute: typeof AuthenticatedMyAuctionsNewRoute
  AuthenticatedPlayersPhoneRoute: typeof AuthenticatedPlayersPhoneRoute
  AuthenticatedMyAuctionsIndexRoute: typeof AuthenticatedMyAuctionsIndexRoute
  AuthenticatedMyAuctionsIdAuctioneerRoute: typeof AuthenticatedMyAuctionsIdAuctioneerRoute
  AuthenticatedMyAuctionsIdEditRoute: typeof AuthenticatedMyAuctionsIdEditRoute
  AuthenticatedMyAuctionsIdIndexRoute: typeof AuthenticatedMyAuctionsIdIndexRoute
  AuthenticatedMyAuctionsIdTeamsTeamIdRoute: typeof AuthenticatedMyAuctionsIdTeamsTeamIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAuctioneerRoute: AuthenticatedAuctioneerRoute,
  AuthenticatedBookmarksRoute: AuthenticatedBookmarksRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAuctionsIdRoute: AuthenticatedAuctionsIdRoute,
  AuthenticatedMyAuctionsNewRoute: AuthenticatedMyAuctionsNewRoute,
  AuthenticatedPlayersPhoneRoute: AuthenticatedPlayersPhoneRoute,
  AuthenticatedMyAuctionsIndexRoute: AuthenticatedMyAuctionsIndexRoute,
  AuthenticatedMyAuctionsIdAuctioneerRoute:
    AuthenticatedMyAuctionsIdAuctioneerRoute,
  AuthenticatedMyAuctionsIdEditRoute: AuthenticatedMyAuctionsIdEditRoute,
  AuthenticatedMyAuctionsIdIndexRoute: AuthenticatedMyAuctionsIdIndexRoute,
  AuthenticatedMyAuctionsIdTeamsTeamIdRoute:
    AuthenticatedMyAuctionsIdTeamsTeamIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  RegisterPlayerAuctionIdRoute: RegisterPlayerAuctionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
